version: "3.4"
services:
  nginx:
    image: nginx
    volumes:
      - ./tools/nginx/:/etc/nginx/conf.d/
      - .:/var/www/
    ports:
      - "8000:80"
    links:
      - php
  php:
    image: php:7.4-fpm-alpine
    restart: on-failure
    volumes:
      - .:/var/www/
