name: Run TEST

on:
  pull_request:
  push:
    branches:
      - 'stable'
      - 'dev'

jobs:
  unit-test:
    name: Run Unit test
    continue-on-error: false
    runs-on: 'ubuntu-20.04'

    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: php bin/tests